server:
  port: ${PORT:0}

spring:
  application:
    name: clients-reservations-service
  datasource:
    url: jdbc:mysql://${RESERVATIONS_DB_HOST:localhost}:3306/reservations_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${RESERVATIONS_DB_USER:root}
    password: ${RESERVATIONS_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      biensClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

mes-config-ms:
  commandes-last: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

